#!/bin/bash
#$ -N log_Tensor
#$ -l mem=3G



wget -q https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
bash Miniconda3-latest-Linux-x86_64.sh -b -p "/net/projects/scratch/winter/valid_until_31_July_2020/pfuerste/miniconda"
rm Miniconda3-latest-Linux-x86_64.sh

echo $PATH
export PATH="$/net/projects/scratch/winter/valid_until_31_July_2020/pfuerste/miniconda/bin:$PATH"
echo $PATH

/net/projects/scratch/winter/valid_until_31_July_2020/pfuerste/miniconda/bin/conda create -y --name tensorflow python=3
/net/projects/scratch/winter/valid_until_31_July_2020/pfuerste/miniconda/bin/conda env list
/net/projects/scratch/winter/valid_until_31_July_2020/pfuerste/miniconda/bin/source activate tensorflow
pip3 install absl\-py==0.7.1
pip3 install asn1crypto==0.24.0
pip3 install -q astor==0.8.0
pip3 install -q attrdict==2.0.1
pip3 install -q attrs==19.1.0
pip3 install -q audioread==2.1.8
pip3 install -q backcall==0.1.0
pip3 install -q bcrypt==3.1.7
pip3 install -q beautifulsoup4==4.8.0
pip3 install -q bleach==3.1.0
pip3 install -q bs4==0.0.1
pip3 install -q certifi==2019.6.16
pip3 install -q cffi==1.12.3
pip3 install -q chardet==3.0.4
pip3 install -q colorama==0.4.1
pip3 install -q cryptography==2.7
pip3 install -q cycler==0.10.0
pip3 install -q decorator==4.4.0
pip3 install -q defusedxml==0.6.0
pip3 install -q entrypoints==0.3
pip3 install -q gast==0.2.2
pip3 install -q google\-pasta==0.1.7
pip3 install -q grpcio==1.22.0
pip3 install -q h5py==2.9.0
pip3 install -q idna==2.8
pip3 install -q ipykernel==5.1.1
pip3 install -q ipython==7.6.1
pip3 install -q ipython\-genutils==0.2.0
pip3 install -q ipywidgets==7.5.0
pip3 install -q jedi==0.14.1
pip3 install -q Jinja2==2.10.1
pip3 install -q joblib==0.13.2
pip3 install -q jsonschema==3.0.1
pip3 install -q jupyter==1.0.0
pip3 install -q jupyter\-client==5.3.1
pip3 install -q jupyter\-console==6.0.0
pip3 install -q jupyter\-core==4.5.0
pip3 install -q Keras==2.2.4
pip3 install -q Keras\-Applications==1.0.8
pip3 install -q Keras\-Preprocessing==1.1.0
pip3 install -q kiwisolver==1.1.0
pip3 install -q librosa==0.7.0
pip3 install -q llvmlite==0.29.0
pip3 install -q Markdown==3.1.1
pip3 install -q MarkupSafe==1.1.1
pip3 install -q matplotlib==3.1.1
pip3 install -q mistune==0.8.4
pip3 install -q nbconvert==5.5.0
pip3 install -q nbformat==4.4.0
pip3 install -q notebook==6.0.0
pip3 install -q numba==0.44.1
pip3 install -q numpy==1.15.4
pip3 install -q pandas==0.25.0
pip3 install -q pandocfilters==1.4.2
pip3 install -q paramiko==2.6.0
pip3 install -q parso==0.5.1
pip3 install -q pickleshare==0.7.5
pip3 install -q progressbar2==3.42.0
pip3 install -q prometheus\-client==0.7.1
pip3 install -q prompt\-toolkit==2.0.9
pip3 install -q protobuf==3.9.0
pip3 install -q pycparser==2.19
pip3 install -q Pygments==2.4.2
pip3 install -q PyNaCl==1.3.0
pip3 install -q pyparsing==2.4.0
pip3 install -q pyrsistent==0.15.3
pip3 install -q python\-dateutil==2.8.0
pip3 install -q python\-speech-features==0.6
pip3 install -q python\-utils==2.3.0
pip3 install -q pytz==2019.1
pip3 install -q pywinpty==0.5.5
pip3 install -q pyxdg==0.26
pip3 install -q PyYAML==5.1.1
pip3 install -q pyzmq==18.0.2
pip3 install -q qtconsole==4.5.1
pip3 install -q requests==2.22.0
pip3 install -q resampy==0.2.1
pip3 install -q scikit\-learn==0.21.2
pip3 install -q scipy==1.3.0
pip3 install -q Send2Trash==1.5.0
pip3 install -q six==1.12.0
pip3 install -q sklearn==0.0
pip3 install -q SoundFile==0.10.2
pip3 install -q soupsieve==1.9.2
pip3 install -q sox==1.3.7
pip3 install -q tensorboard==1.10.0
pip3 install -q tensorflow==1.14.0
pip3 install -q tensorflow\-estimator==1.14.0
pip3 install -q tensorflow\-gpu==1.10.0
pip3 install -q termcolor==1.1.0
pip3 install -q terminado==0.8.2
pip3 install -q testpath==0.4.2
pip3 install -q tornado==6.0.3
pip3 install -q tqdm==4.32.2
pip3 install -q traitlets==4.3.2
pip3 install -q urllib3==1.25.3
pip3 install -q wcwidth==0.1.7
pip3 install -q webencodings==0.5.1
pip3 install -q Werkzeug==0.15.4
pip3 install -q widgetsnbextension==3.5.0
pip3 install -q wrapt==1.11.2

conda list
source deactivate tensorflow

cd /net/projects/scratch/winter/valid_until_31_July_2020/pfuerste/miniconda/pkgs
rm *.tar.bz2 -f 2> /dev/null
